### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by irabro1992** [kirodewal/TgIndexPro#1]
when i try to generate session string , i got this error message.
i already replace app id , app hash & chat id in .env.

TgIndexPro-HxBots\TgIndexPro-HxBots\app\generate_session_string.py", line 15, in <module>
    api_id = os.environ['API_ID']#int(input("Enter your API_ID: "))
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'API_ID'

**Comment by irabro1992** [comment]
and i also configured api_ID and api hash in generate_session_string.py.
but still error.any tip ?

**Comment by kirodewal** [comment]
Use telegram bot https://t.me/stringsessionbot

**Comment by kirodewal** [comment]
Replace APP_ID, API_HASH at here :- app/config.py
